#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef enum { TOK_EOF, TOK_INT, TOK_RETURN, TOK_FOR, TOK_IDENT, TOK_NUM, TOK_LP='(', TOK_RP=')', TOK_LB='{', TOK_RB='}', TOK_SEMI=';', TOK_ASSIGN='=', TOK_PLUS='+', TOK_LT='<', TOK_COMMA=',' } TokenKind;
typedef struct { TokenKind kind; char text[64]; long value; } Token;
static const char *src; static Token tok;
static void next(void){ while(isspace((unsigned char)*src)) src++; memset(&tok,0,sizeof tok); if(!*src){tok.kind=TOK_EOF;return;} char c=*src; if(isalpha((unsigned char)c)||c=='_'){int n=0; while(isalnum((unsigned char)*src)||*src=='_'){ if(n<63) tok.text[n++]=*src; src++; } tok.text[n]=0; if(!strcmp(tok.text,"int")) tok.kind=TOK_INT; else if(!strcmp(tok.text,"return")) tok.kind=TOK_RETURN; else if(!strcmp(tok.text,"for")) tok.kind=TOK_FOR; else tok.kind=TOK_IDENT; return;} if(isdigit((unsigned char)c)){ long v=0; while(isdigit((unsigned char)*src)){v=v*10+(*src-'0'); src++;} tok.kind=TOK_NUM; tok.value=v; return;} tok.kind=(TokenKind)c; tok.text[0]=c; tok.text[1]=0; src++; }
static void die(const char *m){ fprintf(stderr,"parse error: %s near '%s'\n",m,tok.text); exit(1);} static void expect(TokenKind k){ if(tok.kind!=k) die("unexpected token"); next(); }

typedef enum { N_NUM,N_VAR,N_ASSIGN,N_ADD,N_LT,N_RETURN,N_BLOCK,N_FOR,N_EXPRSTMT } NodeKind;
typedef struct Node Node; struct Node{ NodeKind kind; long val; char name[64]; Node *lhs,*rhs,*init,*cond,*inc,*body; Node **stmts; int nstmts; };
static Node *node(NodeKind k){ Node *n=calloc(1,sizeof(Node)); if(!n){perror("calloc");exit(1);} n->kind=k; return n; }
static char vars[128][64]; static int nvars; static int var_index(const char *s){ for(int i=0;i<nvars;i++) if(!strcmp(vars[i],s)) return i; if(nvars>=128) die("too many variables"); strcpy(vars[nvars],s); return nvars++; }
static Node *expr(void); static Node *stmt(void);
static Node *primary(void){ if(tok.kind==TOK_NUM){Node*n=node(N_NUM); n->val=tok.value; next(); return n;} if(tok.kind==TOK_IDENT){Node*n=node(N_VAR); strcpy(n->name,tok.text); var_index(tok.text); next(); return n;} if(tok.kind==TOK_LP){next(); Node*n=expr(); expect(TOK_RP); return n;} die("expected primary expression"); return NULL; }
static Node *add(void){ Node*n=primary(); while(tok.kind==TOK_PLUS){next(); Node*r=node(N_ADD); r->lhs=n; r->rhs=primary(); n=r;} return n; }
static Node *rel(void){ Node*n=add(); while(tok.kind==TOK_LT){next(); Node*r=node(N_LT); r->lhs=n; r->rhs=add(); n=r;} return n; }
static Node *expr(void){ Node*n=rel(); if(tok.kind==TOK_ASSIGN){ if(n->kind!=N_VAR) die("left side of assignment must be a variable"); next(); Node*r=node(N_ASSIGN); r->lhs=n; r->rhs=expr(); return r;} return n; }
static Node *expr_stmt_until(TokenKind end){ if(tok.kind==end) return NULL; Node*n=node(N_EXPRSTMT); n->lhs=expr(); return n; }
static Node *block(void){ Node*b=node(N_BLOCK); expect(TOK_LB); while(tok.kind!=TOK_RB && tok.kind!=TOK_EOF){ b->stmts=realloc(b->stmts,sizeof(Node*)*(b->nstmts+1)); b->stmts[b->nstmts++]=stmt(); } expect(TOK_RB); return b; }
static Node *stmt(void){ if(tok.kind==TOK_INT){ next(); if(tok.kind!=TOK_IDENT) die("expected variable name"); char name[64]; strcpy(name,tok.text); var_index(name); next(); Node *n=NULL; if(tok.kind==TOK_ASSIGN){ next(); Node*v=node(N_VAR); strcpy(v->name,name); Node*a=node(N_ASSIGN); a->lhs=v; a->rhs=expr(); n=node(N_EXPRSTMT); n->lhs=a; } expect(TOK_SEMI); return n?n:node(N_BLOCK); } if(tok.kind==TOK_RETURN){ next(); Node*n=node(N_RETURN); n->lhs=expr(); expect(TOK_SEMI); return n; } if(tok.kind==TOK_FOR){ Node*n=node(N_FOR); next(); expect(TOK_LP); n->init=expr_stmt_until(TOK_SEMI); expect(TOK_SEMI); n->cond=expr_stmt_until(TOK_SEMI); expect(TOK_SEMI); n->inc=expr_stmt_until(TOK_RP); expect(TOK_RP); n->body=(tok.kind==TOK_LB)?block():stmt(); return n; } if(tok.kind==TOK_LB) return block(); Node*n=node(N_EXPRSTMT); n->lhs=expr(); expect(TOK_SEMI); return n; }
static Node *program(void){ expect(TOK_INT); if(tok.kind!=TOK_IDENT || strcmp(tok.text,"main")) die("only int main() is supported"); next(); expect(TOK_LP); expect(TOK_RP); return block(); }
static FILE *out; static int label_id;
static int off(const char*s){ return (var_index(s)+1)*8; }
static void gen(Node*n){ if(!n) return; switch(n->kind){ case N_NUM: fprintf(out,"  mov $%ld, %%rax\n",n->val); break; case N_VAR: fprintf(out,"  mov -%d(%%rbp), %%rax\n",off(n->name)); break; case N_ASSIGN: gen(n->rhs); fprintf(out,"  mov %%rax, -%d(%%rbp)\n",off(n->lhs->name)); break; case N_ADD: gen(n->lhs); fprintf(out,"  push %%rax\n"); gen(n->rhs); fprintf(out,"  pop %%rcx\n  add %%rcx, %%rax\n"); break; case N_LT: gen(n->lhs); fprintf(out,"  push %%rax\n"); gen(n->rhs); fprintf(out,"  pop %%rcx\n  cmp %%rax, %%rcx\n  setl %%al\n  movzb %%al, %%rax\n"); break; case N_EXPRSTMT: gen(n->lhs); break; case N_RETURN: gen(n->lhs); fprintf(out,"  jmp .L.return\n"); break; case N_BLOCK: for(int i=0;i<n->nstmts;i++) gen(n->stmts[i]); break; case N_FOR:{ int id=label_id++; gen(n->init); fprintf(out,".L.for.cond.%d:\n",id); if(n->cond){ gen(n->cond); fprintf(out,"  cmp $0, %%rax\n  je .L.for.end.%d\n",id);} gen(n->body); gen(n->inc); fprintf(out,"  jmp .L.for.cond.%d\n.L.for.end.%d:\n",id,id); break;} }}
static char *read_file(const char *p){ FILE*f=fopen(p,"rb"); if(!f){perror(p);exit(1);} fseek(f,0,SEEK_END); long n=ftell(f); rewind(f); char*b=malloc(n+1); fread(b,1,n,f); b[n]=0; fclose(f); return b; }
int main(int argc,char**argv){ if(argc!=4 || strcmp(argv[2],"-o")){ fprintf(stderr,"usage: %s input.c -o output_exe\n",argv[0]); return 2;} src=read_file(argv[1]); next(); Node*ast=program(); char asmfile[512]; snprintf(asmfile,sizeof asmfile,"%s.s",argv[3]); out=fopen(asmfile,"w"); if(!out){perror(asmfile);return 1;} int stack=((nvars*8+15)/16)*16; fprintf(out,".globl main\nmain:\n  push %%rbp\n  mov %%rsp, %%rbp\n  sub $%d, %%rsp\n",stack); gen(ast); fprintf(out,"  mov $0, %%rax\n.L.return:\n  mov %%rbp, %%rsp\n  pop %%rbp\n  ret\n.section .note.GNU-stack,\"\",@progbits\n"); fclose(out); char cmd[1200]; snprintf(cmd,sizeof cmd,"gcc -no-pie %s -o %s",asmfile,argv[3]); int rc=system(cmd); return rc==0?0:1; }
